[package]
edition.workspace = true
name = "stratosphere-core"
version = "0.0.1"

[lints]
workspace = true

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { workspace = true }
proc-macro2 = "1.0"
quote = "1.0"
regex-lite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = "0.1.17"
strum = { version = "0.27.1", features = ["derive"] }
syn = "2.0.106"
