[package]
name = "manager"
version = "0.0.1"
edition.workspace = true

[lints]
workspace = true

[dependencies]
cbt.workspace = true
clap = { version = "4.5", features = ["derive"] }
env_logger.workspace = true
flate2 = "1.0"
indoc = "2"
log.workspace = true
pg-ephemeral = { path = "../pg-ephemeral" }
sha2.workspace = true
tar = "0.4"
url.workspace = true
