[package]
name = "pg-ephemeral"
version = "0.0.1-pre2"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Ephemeral PostgreSQL instances for testing"
license = "MIT"
repository = "https://github.com/mbj/mrs/tree/main/pg-ephemeral"
readme = "README.md"
keywords = ["postgres", "postgresql", "testing", "database"]
categories = ["development-tools::testing"]

[lints]
workspace = true

[dependencies]
ociman = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
hex = { workspace = true }
indexmap = { version = "2.7", features = ["serde"] }
log = { workspace = true }
nom = { workspace = true }
pg-client = { workspace = true }
rand = { workspace = true }
rcgen = "0.13"
serde = { workspace = true }
serde_json = { workspace = true }
semver = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
time = "0.3"
tokio = { workspace = true, features = ["io-std", "macros", "rt"] }
toml = "0.9.5"
x509-parser = { version = "0.18", features = ["verify"] }

[dev-dependencies]
indoc = "2"

[[bin]]
name = "pg-ephemeral"
