[package]
name = "pg-ephemeral"
version = "0.0.1"
edition.workspace = true

[lints]
workspace = true

[dependencies]
cbt = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
hex = { workspace = true }
indexmap = { version = "2.7", features = ["serde"] }
log = { workspace = true }
mmigration = { workspace = true }
nom = { workspace = true }
pg-client = { workspace = true }
rand = { workspace = true }
rcgen = "0.13"
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
time = "0.3"
tokio = { workspace = true, features = ["io-std", "macros", "rt"] }
toml = "0.9.5"
x509-parser = { version = "0.18", features = ["verify"] }

[dev-dependencies]
indoc = "2"

[[bin]]
name = "pg-ephemeral"
