[package]
name = "pg-client"
version = "0.0.1"
edition.workspace = true

[lints]
workspace = true

[dependencies]
hostname-validator = "1.1.1"
serde = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
url = "2.5.7"

[dev-dependencies]
cbt = { workspace = true }
pg-ephemeral = { workspace = true }
serde_json.workspace = true
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
